os:
  - osx
language: generic

osx_image: xcode14.2

cache:
  directories:
    - ~/.pub-cache
    - ~/Library/Caches/flutter

install:
  - git clone https://github.com/flutter/flutter.git -b 3.7.12
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter precache

script:
  - flutter build macos

before_deploy:
  - cd build/macos/Build/Products/Release
  - zip -r 东油课表.zip 东油课表.app
  - cd -

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/macos/Build/Products/Release/东油课表.zip
  skip_cleanup: true