os:
  - linux
  - osx

dist: trusty  # for Linux builds

language: generic

cache:
  directories:
    - ~/.pub-cache
    - ~/Library/Caches/flutter

install:
  - git clone https://github.com/flutter/flutter.git -b 3.7.12
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter precache

script:
  # Build Linux version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      flutter build linux;
    fi

  # Build macOS version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      flutter build macos;
    fi