version: 2.1
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        xcode: [12.5.1, 13.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - name: Install dependencies
      run: flutter pub get
    - name: Build app
      run: flutter build ${{ matrix.os == 'windows-latest' && 'windows' || 'macos' }}
